let g:notes_directories = ['~/Dropbox/vim_notes']
let g:notes_suffix = '.txt'
let g:notes_smart_quotes = 0
let g:notes_unicode_enabled = 0
let g:notes_conceal_code = 0
"let g:notes_conceal_italic = 0
"let g:notes_conceal_bold = 0
let g:notes_conceal_url = 0
highlight link notesCodeStart Comment
highlight link notesCodeEnd Comment
